logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.hotel=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always
server.port=8080
# -------------------------------------------------
# DATABASE – MySQL
# -------------------------------------------------
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=never
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# -------------------------------------------------
# EMAIL SETTINGS (Gmail example)
# -------------------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lifangaming2@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD:YOUR_GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.default-encoding=UTF-8

# -------------------------------------------------
# OAUTH2 – Google
# -------------------------------------------------
spring.security.oauth2.client.registration.google.client-id=425788274897-s27it71ni58gksgnkqbgrqq800g400d5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# Frontend Redirect URL after Google Login
app.frontend.url=http://localhost:3000
