logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.level.com.hotel=INFO
server.error.include-message=always
server.error.include-stacktrace=always
server.port=8080
# -------------------------------------------------
# DATABASE – PostgreSQL (Supabase/Railway)
# -------------------------------------------------
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hotel_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# HikariCP settings for Cloud DB
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=never
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# -------------------------------------------------
# EMAIL SETTINGS (Gmail example)
# -------------------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lifangaming2@gmail.com
spring.mail.password=zpka heyj oqwa zysj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=false
spring.mail.default-encoding=UTF-8

# -------------------------------------------------
# OAUTH2 – Google
# -------------------------------------------------
spring.security.oauth2.client.registration.google.client-id=425788274897-s27it71ni58gksgnkqbgrqq800g400d5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# Frontend Redirect URL after Google Login
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

# -----------------------------
# Cloudinary configuration
# Set these as environment variables in production (CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET)
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
